services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - 8030:27017
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - 8020:8020
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env

volumes:
  mongo-data:
